#!/bin/bash

echo -e "Please enter the short name for the new project"
echo -e "(Note: this name is used in the project's URL)\n"
printf "Project's short name ( a-z, A-Z, 0-9, _ ): "
read project_name

echo -e "Creating images folder for the project: ./img/$project_name/"
mkdir ./img/$project_name

echo -e "Creating the page for the project: ./projects/$project_name.html"
echo -e "---\nlayout: project\nproject: $project_name\n---" >> ./projects/$project_name.html

echo -e "Creating a new project record in _data/projects.yaml"
echo -e "$project_name:" >> ./_data/projects.yaml
echo -e "  url: $project_name" >> ./_data/projects.yaml
echo -e "  title: New Project" >> ./_data/projects.yaml
echo -e "  description: Blah Blah Blah" >> ./_data/projects.yaml
echo -e "  main_image: img/$project_name/main.jpg" >> ./_data/projects.yaml
echo -e "  images:\n    -\n    -" >> ./_data/projects.yaml
echo -e "  videos:\n    -\n    -\n" >> ./_data/projects.yaml

echo -e "Done. Now edit the new record in _data/projects.yaml and you're ready to go."